### ISSUE TITLE
Implement CustomLinkedlist class with Add method.

### ISSUE THREAD

**Issue by furkankocyigit** [samedkocyigit/interview-questions#13]
Create a new Class named CustomLinkedList. 
This class will have one head Node (another class) which holds integer data and points to the next Node.
to give an example, the behavior should something similar to the following:

CustomLinkedList list = new CustomLinkedList();
list.add(1);
list.add(2);
list.add(3);

list should represent: 1->2->3->null
where '1' is head here.

**Comment by samedkocyigit** [comment]
do i create a new resource file? or should i create the new class in the same source file?

**Comment by furkankocyigit** [comment]
Create a new source file either in the same directory or create a new directory.
In general, any class definition should be its own source file.
